// Auto-generated index file for split translations
// DO NOT EDIT THIS FILE MANUALLY

import account from "./account.json"
import autoApprove from "./autoApprove.json"
import banner from "./banner.json"
import bannerCarousel from "./bannerCarousel.json"
import browser from "./browser.json"
import buttonConfig from "./buttonConfig.json"
import chat from "./chat.json"
import chatTextArea from "./chatTextArea.json"
import checkpointControls from "./checkpointControls.json"
import clineRules from "./clineRules.json"
import common from "./common.json"
import debugSection from "./debugSection.json"
import errorRow from "./errorRow.json"
import history from "./history.json"
import historyPreview from "./historyPreview.json"
import hookRow from "./hookRow.json"
import imagePreview from "./imagePreview.json"
import mcp from "./mcp.json"
import modelInfo from "./modelInfo.json"
import modelPicker from "./modelPicker.json"
import navigation from "./navigation.json"
import newRuleRow from "./newRuleRow.json"
import onboarding from "./onboarding.json"
import openRouter from "./openRouter.json"
import ruleRow from "./ruleRow.json"
import serversToggleModal from "./serversToggleModal.json"
import settings from "./settings.json"
import taskHeader from "./taskHeader.json"
import telemetryBanner from "./telemetryBanner.json"
import terminal from "./terminal.json"
import welcome from "./welcome.json"
import whatsNew from "./whatsNew.json"

const translation = {
	...account,
	...autoApprove,
	...banner,
	...bannerCarousel,
	...browser,
	...buttonConfig,
	...chat,
	...chatTextArea,
	...checkpointControls,
	...clineRules,
	...common,
	...debugSection,
	...errorRow,
	...history,
	...historyPreview,
	...hookRow,
	...imagePreview,
	...mcp,
	...modelInfo,
	...modelPicker,
	...navigation,
	...newRuleRow,
	...onboarding,
	...openRouter,
	...ruleRow,
	...serversToggleModal,
	...settings,
	...taskHeader,
	...telemetryBanner,
	...terminal,
	...welcome,
	...whatsNew,
}

export default translation
